sudo: false
language: node_js
before_install:
  - sudo apt-get -qq update
  - wget http://sourceforge.net/projects/libpng/files/libpng16/1.6.34/libpng-1.6.34.tar.gz/download -O libpng.tar.gz && tar -xvf libpng.tar.gz && cd libpng-1.6.34 && sudo bash configure --prefix=/usr/local/libpng && sudo make install
node_js:
  - 9
  - 8
  - 6
